import Head from "next/head";

// components
import Article from "../src/Components/Article/Article";

export default function Articles() {
    return (
      <>
        <Head>
          <title>Nashiryot</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

      <Article/>
      </>
    );
}