import Head from "next/head";
import LitCalendar from "../src/Components/LitCalendar/LitCalendar";
import Click from "../src/Components/Click/Click";

export default function Calendar() {
  return (
    <>
      <Head>
        <title>Nashiryot</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <LitCalendar/>
     <Click/>

    </>
  );
}