import Head from "next/head";

import Book from "../src/Components/book/book";
import Books from "../src/Components/books/boks";
import Contact from "../src/Components/contact/contact";
import ElJournal from "../src/Components/ElJournal/ElJournal";
import Journallar from "../src/Components/journallar/Journallar";
import Layout from "../src/Components/layout/layout";
import Partners from "../src/Components/partners/partners";
import Seemore from "../src/Components/seemore/seemore";
import Link from "next/link"
import Click from "../src/Components/Click/Click"
import ListArr from "../faceBackend/list"
import JournallarArr from "../faceBackend/jurnal"
import BookArr from "../faceBackend/book"

export default function Home() {
  return (
    <>
      <Head>
        <title>Nashiryot</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="nav__link">
        <div className="container">
          <ul className="nav__link--list">
            {
              ListArr && ListArr.map(e => (
                <li className="nav__link--item" key={e.id}>
                  <Link href={e.href}>
                    <a className="nav__link--link">
                      {e.title}
                    </a>
                  </Link>
                </li>
              ))
            }
          </ul>
        </div>
      </section>

      <section className="Books">
        <div className="container">
          <Books />
        </div>
      </section>

      <section className="ElektronJurnal" >
        <div className="container">
          <h3 className="ElektroJurnal_Title">
            Elektron journal
          </h3>
          <ElJournal />
        </div>
      </section>
      <section className="Journallar">
        <div className="container">
          <h3 className="Journallar__title">
            Journallar
          </h3>
          <Journallar JournallarAr={JournallarArr.slice(0, 4)} />
          <Seemore />
        </div>
      </section>
      <section className="Media">
        <div className="container">
          <h3 className="Media_title">
            Media kontent
          </h3>
        </div>
      </section>
      <section className="Book">
        <div className="container">
          <h3 className="Book_title">
            Kitoblar
          </h3>
          <Book Arr={BookArr.slice(0, 4)} />
          <Seemore />
        </div>
      </section>
      <section className="Partners">
        <div className="container">
          <h3 className="Partners_title">
            Bizning hamkorlar
          </h3>
          <Partners />
        </div>
      </section>
      <section className="Click">
        <Click />
      </section>
      <section className="Contact">
        <div className="container">
          <h3 className="Contact_title">Biz bilan bog'lanish</h3>
          <hr className="Contact--line" />
          <Contact />
        </div>
      </section>
    </>
  );
}
