import Head from "next/head";

// components
import Magazines from "../src/Components/Magazines/Magazines";
import Economy from "../src/Components/Economy/Economy";
import WorldNews from "../src/Components/World-news/World_news";
import Uzbek from "../src/Components/Uzbek-news/Uzbek_news";
import VideoNews from "../src/Components/Video-news/Video_news";

export default function MediaMagazines() {
    return (
      <>
        <Head>
          <title>Nashiryot</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
   
      <Magazines/>
      <Economy/>
      <WorldNews/>
      <Uzbek/>
      <VideoNews/>
      </>
    );
}