import Head from "next/head";

// components
import Media from "../src/Components/Media/Media";

export default function MediaContent() {
    return (
      <>
        <Head>
          <title>Nashiryot</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
   
      <Media/>
      </>
    );
}