import Head from "next/head";

// components
import Vacancy from "../src/Components/Vacancy/Vacancy";

export default function VacancyCost() {
    return (
      <>
        <Head>
          <title>Nashiryot</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
   
      <Vacancy/>
      </>
    );
}